[package]
name = "opsgate-api"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "opsgate-api"
path = "src/main.rs"

[dependencies]
opsgate-core.workspace = true
opsgate-db.workspace = true
opsgate-model.workspace = true
opsgate-service.workspace = true

tokio.workspace = true
tokio-util.workspace = true
axum.workspace = true
tower.workspace = true
tower-http.workspace = true
sqlx.workspace = true

serde.workspace = true
serde_json.workspace = true
validator.workspace = true
config.workspace = true
secrecy.workspace = true

tracing.workspace = true
tracing-subscriber.workspace = true
dotenvy.workspace = true
anyhow.workspace = true

aliri.workspace = true
aliri_oauth2.workspace = true
aliri_clock.workspace = true
jsonwebtoken.workspace = true
openidconnect.workspace = true
reqwest.workspace = true
url.workspace = true
axum-extra.workspace = true
subtle.workspace = true
rmcp.workspace = true
chrono.workspace = true
uuid.workspace = true
thiserror.workspace = true
schemars.workspace = true
time.workspace = true

[dev-dependencies]
base64.workspace = true

[lints]
workspace = true
